version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.0.0
    steps:
      - checkout
      - run: npm install
      - run: test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build

# version: 2.1
# jobs:
#   build:
#     docker:
#       - image: cimg/node:14.0.0
#     steps:
#       - checkout
#       - run: 
#         - name: npm install
#         - command: npm install
#       - run:
#         - name: test
#         - command: npm test
# workflows:
#   build_and_test:
#     jobs:
#       - build